# Generated by Django 4.2.2 on 2023-06-16 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_toy_alter_feeding_options_alter_feeding_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='poke',
            name='toys',
            field=models.ManyToManyField(to='main_app.toy'),
        ),
    ]
